project_id = "cuidofxidstqpgypxcop"

[functions.shopify-update-product-tags]
verify_jwt = true

[functions.shopify-update-product]
verify_jwt = true

[functions.shopify-sync-pending]
verify_jwt = true
