project_id = "cuidofxidstqpgypxcop"

[functions.shopify-update-product-tags]
verify_jwt = true

[functions.shopify-update-product]
verify_jwt = true

[functions.shopify-sync-pending]
verify_jwt = true

[functions.shopify-sync-product-images]
verify_jwt = true

[functions.shopify-sync-product-variants]
verify_jwt = true

[functions.submit-catalog-order]
verify_jwt = false

[functions.mockup-upload-url]
verify_jwt = false

[functions.design-signed-url]
verify_jwt = true
