// Shared test setup for BOTH environments.
//
// Most of this repo's tests run under the `node` environment (see
// vitest.config.ts) where there is no document at all, so everything here is
// guarded rather than assumed. A file that opts into jsdom with
// `// @vitest-environment jsdom` gets the DOM matchers and the matchMedia stub;
// a node test gets neither and does not pay for them.
if (typeof window !== "undefined") {
  await import("@testing-library/jest-dom/vitest");

  // jsdom implements no media queries. Any component that asks gets "no match"
  // rather than a crash.
  // jsdom implements no IntersectionObserver, and the entity workspace uses one
  // to keep its pipeline rail in sync with the scroll position. A no-op is the
  // honest stub: nothing scrolls in a test, so nothing should ever intersect.
  if (typeof globalThis.IntersectionObserver === "undefined") {
    class NoopIntersectionObserver implements IntersectionObserver {
      readonly root = null;
      readonly rootMargin = "";
      readonly thresholds: ReadonlyArray<number> = [];
      observe() {}
      unobserve() {}
      disconnect() {}
      takeRecords(): IntersectionObserverEntry[] {
        return [];
      }
    }
    Object.defineProperty(globalThis, "IntersectionObserver", {
      value: NoopIntersectionObserver,
      writable: true,
    });
  }

  // jsdom does not implement scrollIntoView either.
  if (!Element.prototype.scrollIntoView) {
    Element.prototype.scrollIntoView = () => {};
  }

  Object.defineProperty(window, "matchMedia", {
    writable: true,
    value: (query: string) => ({
      matches: false,
      media: query,
      onchange: null,
      addListener: () => {},
      removeListener: () => {},
      addEventListener: () => {},
      removeEventListener: () => {},
      dispatchEvent: () => {},
    }),
  });
}

// A localStorage that exists.
//
// `src/integrations/supabase/client.ts` reads `localStorage` at module scope,
// so ANY module that transitively imports the Supabase client — ten of this
// repo's test files do — throws on import under the node environment. That file
// is generated by Lovable and carries a "do not edit" banner, so the shim lives
// here instead of there.
//
// In-memory and per-process: no test should be relying on persistence, and if
// one ever does, it will fail loudly rather than leak state between files.
if (typeof globalThis.localStorage === "undefined") {
  const store = new Map<string, string>();
  const memoryStorage: Storage = {
    get length() {
      return store.size;
    },
    clear: () => store.clear(),
    getItem: (key: string) => store.get(key) ?? null,
    key: (index: number) => [...store.keys()][index] ?? null,
    removeItem: (key: string) => void store.delete(key),
    setItem: (key: string, value: string) => void store.set(key, String(value)),
  };
  Object.defineProperty(globalThis, "localStorage", { value: memoryStorage, writable: true });
  Object.defineProperty(globalThis, "sessionStorage", { value: memoryStorage, writable: true });
}
